<a href="https://colab.research.google.com/github/andreaeusebi/pytorch_for_deep_learning/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(size=(7, 7))
print(f"random_tensor:\n{random_tensor}\nShape: {random_tensor.shape}")

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))
print(f"random_tensor_2:\n{random_tensor_2}\nShape: {random_tensor_2.shape}")

# Perform matrix multiplication
# A @ B - A = 7 x 7 , B = 1 x 7

mat_mul = torch.matmul(random_tensor, random_tensor_2.T)
print(f"mat_mul:\n{mat_mul}\nShape: {mat_mul.shape}")

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)


# Create two random tensors
random_tensor_A = torch.rand(size=(7, 7))
random_tensor_B = torch.rand(size=(1, 7))

print(random_tensor_A)
print(random_tensor_B)

# Matrix multiply tensors
mat_mul = torch.matmul(random_tensor_A, random_tensor_B.T)
print(mat_mul)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
CUDA_RANDOM_SEED = 1234
torch.cuda.manual_seed(CUDA_RANDOM_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(f"Cuda is available? {torch.cuda.is_available()}")

# Create two random tensors on GPU

# Create tensor (default on CPU)
tensor_1 = torch.rand(size=(2, 3))
tensor_2 = torch.rand(size=(2, 3))

# Tensor not on GPU
print(tensor_1, tensor_1.device)
print(tensor_2, tensor_2.device)

# Move tensor to GPU (if available)
tensor_1_on_gpu = tensor_1.to("cuda")
tensor_2_on_gpu = tensor_2.to("cuda")
print(tensor_1_on_gpu, tensor_1_on_gpu.device)
print(tensor_2_on_gpu, tensor_2_on_gpu.device)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mat_mul_2 = torch.matmul(tensor_1_on_gpu, tensor_2_on_gpu.T)
print(mat_mul_2, mat_mul_2.shape)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"Maximum: {mat_mul_2.max()}")

# Find min
print(f"Minimum: {mat_mul_2.min()}")

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Index where max value occurs: {mat_mul_2.argmax()}")

# Find arg min
print(f"Index where min value occurs: {mat_mul_2.argmin()}")


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor_3 = torch.rand(size=(1, 1, 1, 10))
print(f"tensor_3:\n{tensor_3}\nShape: {tensor_3.shape}")


# Remove single dimensions
tensor_4 = torch.squeeze(tensor_3)

# Print out tensors and their shapes
print(f"tensor_4:\n{tensor_4}\nShape: {tensor_4.shape}")
